language: java
jdk: openjdk11
script: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: vvFF1duwoC6BtE64wIqR1b1SvefcnIiLu/LXmVut6MKXGuOJQCuStkxMPgEjAXuzzfx2NqHaimrLiyLCVS/gqX0NJd3vXlH+7KLMVLnEqB9MKe2wFXlL3MadbRrdd0UfHHtDepYNnDjI4TPZAB6KGayecozu2R9fsQkeSmadyB5AnUrajmydR8NDC2s0FUUqekcGz3hK6iKbyU1WOvGZhX1Kr/T/mQ+vw02YPpXnms8iLAh58hVoUkvr8WnSr9fDfoE12Age4TOIvecryETpOi2ZwhKHhtx1fiCcv6rsPsWflCgY529iPUWzzGGWM2UKxCHDoNmY0Tu9iontoNKcjHsCh+ZeypDKoH2KVLCvHz/y/C7riey7EywAuYfHnUD40G23FJg+0BOmc20p7n6zkXhh7TnXDhgfy49CJc+7pkEaheeNWjSKEvWXNXhUzdSVxPMtQS1vHgDYBCTy93TmY7xSUEn2T5OBhS4uWIcjGeft5rndqOrc3ILCANp7U7V8/R4PdpuCPcBjvhWJVRDpNGnUPuwnh9c7FJBcmP5oL8/2dAg47MkZajPkYUwbz4puKaJYwzXfBXBSIZusg2HL+3Vx/pm11RcxzSHTeRTDZKhAXQGAXj3nFLIKVhehOAmwx9O3R0iiBg0IV+Y03coFOpL5V60ezSD2yBwqV0/VqqM=
  file_glob: true
  file: target/sonar-zap-plugin-*.jar
  skip_cleanup: true
  on:
    tags: true
