language: java
jdk: openjdk8
script: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: "VWpY4VVP0r3hYQIBl8MyxJFyb53W92hZljxqXoSxAm1YC/tqhttiqwdv7tQEnKVVCq5v44VIVUlGh29YQG/mtiVk4Q9T6fw7AgLQRT6aofxb3WGXKACaGD1r6getpu/lqlmK+eFLRGXJhluk68ZJ/1uKh8LblVdxkzJutl/Mkdc9172+kG3zQCGo9zpIPho2pHjJYiiehPYbohAygydKBnVkNFKyvRAUabNw+O2/kj54ht7zMJ+WWK9fbg6oWNmIRsdwhxmN0bEH9eZG1vAgtUy2tnGfxVDPnkpcnYdX5dRk7SfGduGqMwfXunKCZaipEyhbvocETUsTR26D1+6aHtZe5AQGV9WdPGiyLF+N4LQyDfZ9V6IVpgNXaePIEj3szuslc8fmRYQqWF0rE+E6oM7P0AAnzP//oClcGo/Wt1H2cM9quNDWHN4Ex3u96uFcP3JXWCSvpwFIoRnsc+IjYr1Sbl6KcEk3Ym52BwpHjeNMV/6KQqt7ptgJvTThh7iePJSwv6P4DSoxIIhlrjdb33sZxQXnsgWgmfGSoWmGDh4QNMN+05s4INrf7BsKz0oncNuMNAjKBdhmizs/y8iYWzwqMc0GKV6jvU0wHapYEhpXJ4hWoWAk87T4Ut++mEbjK/RdVLMYbLwVT8T/xw8fRc5mQsjLmokxv2a9JN78AOc="
  file_glob: true
  file: target/sonar-zap-plugin-*.jar
  skip_cleanup: true
  on:
    tags: true
