language: java
jdk: openjdk8
script: mvn clean package
env:
  secure: "iY8ddWI4bt55MkSQnnc1MyxhAz86tR6OPWq4w/yuZ8MKz6cjg2mxUdUskBOLRLBNpTBZFv2cxIS5mfFQKzClKZnm0gA2J+Y0vGyzSWR5fjqimXQyYQqcxryWghOMbG2SArcF3klAfx665NC4Hg0wP9IDr3WslyEfz6ZcRNawlz4MecZN8todCe9RnOBlvYba+25bFolxgazPNjAKdhQLbvhHLvH/+m2MmZCR2KdIxX5iHSVXSeb6ofoXMg5ML8/Q2pH5LRmJW4J7auw7fY8FeY51SW92uHJYkXMmJTzn6mSBA3AO3WNRomwlQPKDwMh/c0+tqax/y6zBzYFz6Z/Yzrqv0m4cPt1M2Fxkoym1k2X7iUtKpeq03CzR2hqSlRHex8QvOc+9sFzd/nLa5dBkdNiMpOwawCtG/Xp4ThVjwyLjVoFJfRzLU+iRZ3rxy7b5xhferDWDHFS/N5FAr57IqUlVlBO9NKSCcSUA5yl1T3gxa5JsrKdgTz1LKIsNEwi+5j0Mr2BZu2OO0fIYddLSIlHn7mbFYoB8oPE8B9pKABRDi02QuPMK9McEEnH+gmmee3QEPRQ5pAXxIdR3PbQzFshN9hx4sLPiTkeNUUupJaiTpbbpNHcJge2rxjknO3M+mCosntubaFnxov3p/tUNXyjWAYsU0SNA4tBklGTttfA="

deploy:
  provider: releases
  api_key:
    secure: "iIpNlCeY40d551a01hes4umEbC7gBePwGIopW8wvFjEeh8/OaOgrTANF7+ijVvTnf12itajcKmCRmkVM3nyfiXvzyINBr3X6HEzWbm72ZZ+re8pAFV96nPDst7mRAKhs/pv0U6tY3dcNKDBCDf9AbyX+5Y5WFugjNxbPDVqvZoXfOJFA2oWkJXkwCju+X+9mYM2p3Cl/BJvr7EAq31C1jNSB6xyTGtR7PMM+lS1F1Df0c86jY2H33vMWOgsnHStflVp04VDrq4LkkEvV90EB4QOguCb7Olkzdq8eoGYmp4ZLtKStInXCxHl7xbVlBvlAHf81Q7Oe8oIOTr2HQoKIwd3BcZafQZBqeRwyPngh9VQjftgjsQCpDXOCIYNLLzBYTcMfcFjEqwQVDOKK1TfsyF0iUctGIFpGaSllZYcjct9hmTNHeJxZrW8J3d5H5ORilb9h4EITEVrmpaJIkmXbdVl2Q8OAsxmaEgvbp/ZEZmnehLX89yM5wRy0NEPtokYbO3pKc57draXnluVHW1QPf+muAuqx8ScEOvM/s+sYj5nVlYcIgU9X8q4rJi+ym8IW0lJskIkfePgLlCgGVD19/aivLnQFLM5iKv3uy67/g4jAk26lQ/VBADtlC8hmu3CHVLQQLhdCOmoDpCT2gH+t/tiOdEUJbRzbCo1zr79Ltsk="
  file_glob: true
  file: target/sonar-zap-plugin-*.jar
  skip_cleanup: true
  on:
    tags: true

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
